package com.kingsaul22.etxcenter.core.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf

enum class Language(val code: String, val displayName: String) {
    EN("en", "English"),
    ES("es", "Español")
}

val LocalLanguage = staticCompositionLocalOf { Language.EN }
val LocalStrings = staticCompositionLocalOf<AppStrings> { AppStrings.English }
val LocalLanguageController = staticCompositionLocalOf<(Language) -> Unit> { {} }

sealed class AppStrings(
    val languageCode: String,
    
    // Top Bar & Navigation
    val appTitle: String,
    val navHome: String,
    val navLive: String,
    val navStats: String,
    val navTeams: String,
    val navPlayers: String,
    
    // Auth & Admin Login
    val adminLogin: String,
    val adminLogout: String,
    val adminModeActive: String,
    val welcomeBackAdmin: String,
    val welcomeToEtx: String,
    val trackFavoriteTeams: String,
    val dbStatusTitle: String,
    val adminLoginTitle: String,
    val emailLabel: String,
    val passwordLabel: String,
    val logIn: String,
    
    // Stats & Match Details
    val matchesPlayed: String,
    val winRate: String,
    val winLoss: String,
    val goalsForShort: String,
    val goalsAgainstShort: String,
    val demosShort: String,
    val matchDetails: String,
    val matchNotFound: String,
    val goBack: String,
    val comparativeStats: String,
    val shots: String,
    val assists: String,
    val saves: String,
    val demos: String,
    
    // Management Dashboard
    val statTeams: String,
    val statPlayers: String,
    val statEvents: String,
    val quickActions: String,
    val actionManageTeams: String,
    val actionManagePlayers: String,
    val actionEditMetadata: String,
    val actionManageCalendar: String,
    val competitionResume: String,
    
    // Manage Teams Screen
    val manageTeamsTitle: String,
    val createNewTeam: String,
    val teamNameLabel: String,
    val logoUrlLabel: String,
    val cancel: String,
    val create: String,
    val delete: String,
    val editRoster: String,
    val deleteTeamConfirmTitle: String,
    val deleteTeamConfirmMsg: String,
    val editRosterTitle: String,
    val save: String,
    val rosterReassignedWarning: String,
    
    // Manage Players Screen
    val managePlayersTitle: String,
    val createPlayer: String,
    val playerNameLabel: String,
    val playerTeamLabel: String,
    val selectTeamPlaceholder: String,
    val deletePlayerConfirmTitle: String,
    val deletePlayerConfirmMsg: String,
    
    // Manage Calendar Screen
    val manageCalendarTitle: String,
    val scheduleNewMatch: String,
    val startTimeLabel: String,
    val endTimeLabel: String,
    val durationLabel: String,
    val timeFormatError: String,
    val deleteCalendarConfirmTitle: String,
    val deleteCalendarConfirmMsg: String,
    val playedStatus: String,
    val scheduledStatus: String,

    // Live Screen
    val liveMatchTitle: String,
    val noActiveMatch: String,
    val liveEvents: String,
    val playerTelemetry: String,
    val blueTeam: String,
    val orangeTeam: String,
    val scoreLabel: String,
    val goalsLabel: String,
    val blueShort: String,
    val orangeShort: String,
    val otBadge: String,
    val winsSuffix: String,
    val finalClock: String,
    val noEventsYet: String,
    val eventsDesc: String,
    val countdownStarted: String,
    val ballHit: String,

    // Players Screen
    val playersDirectoryTitle: String,
    val noTeam: String,

    // Stats Screen
    val matchHistoryTitle: String,
    val noMatchesRecorded: String,

    // Manage Metadata Screen
    val manageMetadataTitle: String,
    val addEntry: String,
    val metadataEmpty: String,
    val editEntryLabel: String,
    val deleteEntryLabel: String,
    val editEntryTitle: String,
    val createEntryTitle: String,
    val keyLabel: String,
    val valueLabel: String,
    val numericLabel: String,
    val deleteMetadataConfirmMsg: String,
    // General
    val loading: String,
    val errorPrefix: String,
    val retry: String
) {
    object English : AppStrings(
        languageCode = "en",
        appTitle = "SAVETX",
        navHome = "Home",
        navLive = "Live",
        navStats = "Stats",
        navTeams = "Teams",
        navPlayers = "Players",
        adminLogin = "Admin Login",
        adminLogout = "Log out Admin",
        adminModeActive = "Admin Mode Active",
        welcomeBackAdmin = "Welcome back, Admin!",
        welcomeToEtx = "Welcome to ETX League!",
        trackFavoriteTeams = "Track your favorite teams and live scores in real-time.",
        dbStatusTitle = "Here's the current database status.",
        adminLoginTitle = "Admin Login",
        emailLabel = "Email",
        passwordLabel = "Password",
        logIn = "Log In",
        matchesPlayed = "Matches Played",
        winRate = "Win%",
        winLoss = "W-L",
        goalsForShort = "GF",
        goalsAgainstShort = "GA",
        demosShort = "Demos",
        matchDetails = "Match Details",
        matchNotFound = "Match not found.",
        goBack = "Go Back",
        comparativeStats = "Comparative Stats",
        shots = "Shots",
        assists = "Assists",
        saves = "Saves",
        demos = "Demos",
        statTeams = "Teams",
        statPlayers = "Players",
        statEvents = "Events",
        quickActions = "Quick Actions",
        actionManageTeams = "Manage Teams",
        actionManagePlayers = "Manage Players",
        actionEditMetadata = "Edit Metadata",
        actionManageCalendar = "Manage Calendar",
        competitionResume = "Competition Resume",
        manageTeamsTitle = "Manage Teams",
        createNewTeam = "Create New Team",
        teamNameLabel = "Team Name",
        logoUrlLabel = "Logo URL (Optional)",
        cancel = "Cancel",
        create = "Create",
        delete = "Delete",
        editRoster = "Edit Roster",
        deleteTeamConfirmTitle = "Delete Team",
        deleteTeamConfirmMsg = "Are you sure you want to delete this team? This will unassign all rostered players.",
        editRosterTitle = "Edit Roster",
        save = "Save",
        rosterReassignedWarning = "Currently on another team",
        managePlayersTitle = "Manage Players",
        createPlayer = "Create Player",
        playerNameLabel = "Display Name",
        playerTeamLabel = "Assign Team",
        selectTeamPlaceholder = "Select a Team",
        deletePlayerConfirmTitle = "Delete Player",
        deletePlayerConfirmMsg = "Are you sure you want to delete this player? This will remove all their cumulative statistics.",
        manageCalendarTitle = "Manage Calendar",
        scheduleNewMatch = "Schedule Upcoming Match",
        startTimeLabel = "Start Window (YYYY-MM-DD HH:mm)",
        endTimeLabel = "End Window (YYYY-MM-DD HH:mm)",
        durationLabel = "Duration (Minutes)",
        timeFormatError = "Invalid date format. Use YYYY-MM-DD HH:mm",
        deleteCalendarConfirmTitle = "Delete Calendar Entry",
        deleteCalendarConfirmMsg = "Are you sure you want to delete this calendar entry?",
        playedStatus = "Played",
        scheduledStatus = "Scheduled",
        loading = "Loading...",
        errorPrefix = "Connection Failed: ",
        retry = "Retry"
    )

    object Spanish : AppStrings(
        languageCode = "es",
        appTitle = "SAVETX",
        navHome = "Inicio",
        navLive = "En Vivo",
        navStats = "Estadísticas",
        navTeams = "Equipos",
        navPlayers = "Jugadores",
        adminLogin = "Acceso Admin",
        adminLogout = "Cerrar sesión Admin",
        adminModeActive = "Modo Admin Activo",
        welcomeBackAdmin = "¡Bienvenido, Administrador!",
        welcomeToEtx = "¡Bienvenido a la Liga ETX!",
        trackFavoriteTeams = "Sigue a tus equipos favoritos y puntajes en vivo en tiempo real.",
        dbStatusTitle = "Estado actual de la base de datos.",
        adminLoginTitle = "Acceso Administrador",
        emailLabel = "Correo electrónico",
        passwordLabel = "Contraseña",
        logIn = "Iniciar sesión",
        matchesPlayed = "Partidos Jugados",
        winRate = "Ganados%",
        winLoss = "G-P",
        goalsForShort = "GF",
        goalsAgainstShort = "GC",
        demosShort = "Demos",
        matchDetails = "Detalles del Partido",
        matchNotFound = "Partido no encontrado.",
        goBack = "Volver",
        comparativeStats = "Estadísticas Comparativas",
        shots = "Tiros",
        assists = "Asistencias",
        saves = "Salvadas",
        demos = "Demoliciones",
        statTeams = "Equipos",
        statPlayers = "Jugadores",
        statEvents = "Eventos",
        quickActions = "Acciones Rápidas",
        actionManageTeams = "Gestionar Equipos",
        actionManagePlayers = "Gestionar Jugadores",
        actionEditMetadata = "Editar Metadatos",
        actionManageCalendar = "Gestionar Calendario",
        competitionResume = "Resumen de Competencia",
        manageTeamsTitle = "Gestionar Equipos",
        createNewTeam = "Crear Nuevo Equipo",
        teamNameLabel = "Nombre del Equipo",
        logoUrlLabel = "URL del Logo (Opcional)",
        cancel = "Cancelar",
        create = "Crear",
        delete = "Eliminar",
        editRoster = "Editar Plantilla",
        deleteTeamConfirmTitle = "Eliminar Equipo",
        deleteTeamConfirmMsg = "¿Estás seguro de que deseas eliminar este equipo? Esto desasignará a todos los jugadores.",
        editRosterTitle = "Editar Plantilla",
        save = "Guardar",
        rosterReassignedWarning = "Actualmente en otro equipo",
        managePlayersTitle = "Gestionar Jugadores",
        createPlayer = "Crear Jugador",
        playerNameLabel = "Nombre de Pantalla",
        playerTeamLabel = "Asignar Equipo",
        selectTeamPlaceholder = "Selecciona un Equipo",
        deletePlayerConfirmTitle = "Eliminar Jugador",
        deletePlayerConfirmMsg = "¿Estás seguro de que deseas eliminar a este jugador? Esto eliminará todas sus estadísticas acumuladas.",
        manageCalendarTitle = "Gestionar Calendario",
        scheduleNewMatch = "Programar Próximo Partido",
        startTimeLabel = "Ventana Inicial (AAAA-MM-DD HH:mm)",
        endTimeLabel = "Ventana Final (AAAA-MM-DD HH:mm)",
        durationLabel = "Duración (Minutos)",
        timeFormatError = "Formato de fecha inválido. Usa AAAA-MM-DD HH:mm",
        deleteCalendarConfirmTitle = "Eliminar Entrada de Calendario",
        deleteCalendarConfirmMsg = "¿Estás seguro de que deseas eliminar esta entrada de calendario?",
        playedStatus = "Jugado",
        scheduledStatus = "Programado",
        loading = "Cargando...",
        errorPrefix = "Error de Conexión: ",
        retry = "Reintentar"
    )

    companion object {
        fun get(language: Language): AppStrings = when (language) {
            Language.EN -> English
            Language.ES -> Spanish
        }
    }
}
